### ISSUE TITLE
SublimeLinter 4 will drop support for tmpdir

### ISSUE THREAD

**Issue by braver** [alecthomas/SublimeLinter-contrib-gometalinter#11]
This plugin is the sole user of the temporary directory feature in SublimeLinter. We intend to remove it from the upcoming version 4. You're free to copy-paste all the relevant code into this repo, or drop the feature as well (if I understand the readme here well enough it doesn't even work for modern version of Go either).

The removal happens here: https://github.com/SublimeLinter/SublimeLinter/pull/870/commits/4904998cb04b51ff242fc354adf5b4065d4ed89e

**Comment by alecthomas** [comment]
Thanks for the heads up, and thanks to all the SublimeLinter folk for the hard work.

**Comment by braver** [comment]
Excellent!
