### ISSUE TITLE
SublimeLinter-contrib-gometalinter is not showing up in SublimeText

### ISSUE THREAD

**Issue by c4milo** [alecthomas/SublimeLinter-contrib-gometalinter#2]
What am I doing wrong?
![](https://cldup.com/9BYwBULjxG.png)

![](https://cldup.com/HEAILyT83G.png)

**Comment by alecthomas** [comment]
The plugin has not been submitted to Package Control, so you'll have to install it manually.

**Comment by c4milo** [comment]
ah, then the current documentation in the README might need to be adjusted.

**Comment by ghost** [comment]
any reason not to submit it to Package Control?

**Comment by samcday** [comment]
+1 - README says this is on Package Control and it isn't! Is it not ready for general consumption yet?

**Comment by oschwald** [comment]
It'd be great for this to be on Package Control. You just need to submit a PR against the [SublimeLinter package control channel](https://github.com/SublimeLinter/package_control_channel). It takes only a few minutes.

**Comment by alecthomas** [comment]
I did actually do this quite some time ago, but for some reason it was extremely onerous. Numerous back and forths about style nits etc. I think I gave up in the end, but I will resubmit it.

**Comment by alecthomas** [comment]
I've submitted the ticket as SublimeLinter/SublimeLinter3#319

**Comment by oschwald** [comment]
:+1:

**Comment by alecthomas** [comment]
https://packagecontrol.io/packages/SublimeLinter-contrib-gometalinter !
