### ISSUE TITLE
plugin_host has exited unexpectedly

### ISSUE THREAD

**Issue by skeggse** [alecthomas/SublimeLinter-contrib-gometalinter#23]
I've been using this package for a few weeks, and have noticed the following message pop up periodically. The package works most of the time, but seems to have some weird interaction with the `plugin_host` that causes it to crash periodically. This only occurs when I'm editing Go files.

```
2018-08-09 11:15:32,912 Running `.../go/bin/gometalinter --fast . -I <file>.go`
error: plugin_host has exited unexpectedly, plugin functionality won't be available until Sublime Text has been restarted
```

I'm running:

- Sublime 3.1.1, build 3176.
- Package Control v3.3.0.
- Sublime-linter 4.7.2.

I'm not seeing anything useful in the ctrl+\` console - what can I do to debug this? I can run `gometalinter` with the same flags from my shell and it works fine.

![image](https://user-images.githubusercontent.com/1348991/43918569-42cfac34-9bc8-11e8-926f-02df26cc02f1.png)

**Comment by otto-md** [comment]
Probably [this](https://github.com/SublimeTextIssues/Core/issues/2327) issue from core Sublime.

**Comment by alecthomas** [comment]
Yes, that is almost certainly it :(

I've had the same problem.

**Comment by skeggse** [comment]
:(
