### ISSUE TITLE
Cannot install gometalinter on Linux x64 (Ubuntu 19.10)

### ISSUE THREAD

**Issue by Alexey-T** [alecthomas/SublimeLinter-contrib-gometalinter#28]
```
Install gometalinter by typing the following in a terminal:
go get github.com/alecthomas/gometalinter
gometalinter --install --update
```

Command-1 runs ok here, command-2 gives "cannot find gometalinter" (so I don't have such binary here). How to install it?

**Comment by alecthomas** [comment]
gometalinter is no longer maintained

**Comment by alecthomas** [comment]
See golangci-lint, and corresponding sublime plugin.
